### ISSUE TITLE
Noto Sans Tifinagh character spacing

### ISSUE THREAD

**Issue by bymat** [notofonts/tifinagh#1]
Hi, we are having an issue using the "Noto Sans Tifinagh".

The problem is that the character U+2D7F appears too close to the next one. It's almost as it's not taking any space. This issue occurs in Firefox and Google Chrome, but Safari is rendering it allright.

Do you know what may be causing this issue?

![image](https://user-images.githubusercontent.com/12187563/27081547-36f38666-5041-11e7-83bc-e1a0fd8e351e.png)

**Comment by simoncozens** [comment]
Both 2D6F and all the mentioned ligatures are now spacing glyph, so this should be fixed.
