### ISSUE TITLE
Erroneous contextual variants of Tifinagh yal and yan

### ISSUE THREAD

**Issue by dscorbett** [notofonts/tifinagh#2]
### Font 
NotoSansTifinagh-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansTifinagh-unhinted.zip
Date: 2017-11-28

### Font Version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+2D4D TIFINAGH LETTER YAL and U+2D4F TIFINAGH LETTER YAN should not have contextual slanted forms. [_The Unicode Standard_, chapter 19](http://www.unicode.org/versions/Unicode10.0.0/ch19.pdf#page=9) has a misleading explanation of Tifinagh’s contextual shaping. [L2/04-142R](http://www.unicode.org/L2/L2004/04142r-n2739r-tifinagh.pdf#page=36), section D. 9 is more complete and explains that these contextual forms do not appear in Neo-Tifinagh. Noto Sans Tifinagh implements Neo-Tifinagh; you can tell because the vertical lines of the yal are joined, which incidentally is why the contextual variation is not needed.

### Character data
ⵍⵍⵍⵏⵏⵍⵏⵏ
U+2D4D TIFINAGH LETTER YAL
U+2D4D TIFINAGH LETTER YAL
U+2D4D TIFINAGH LETTER YAL
U+2D4F TIFINAGH LETTER YAN
U+2D4F TIFINAGH LETTER YAN
U+2D4D TIFINAGH LETTER YAL
U+2D4F TIFINAGH LETTER YAN
U+2D4F TIFINAGH LETTER YAN

### Screenshot
![tifinagh](https://user-images.githubusercontent.com/1124347/33342113-f2fdd23a-d44e-11e7-8cac-ea0404985b53.png)

**Comment by simoncozens** [comment]
From what I understand of the discussion above, since Noto Sans Tifinagh is a Neo-Tifinagh design, the solution here is to remove the special ligatures, so that's what I'll do.

**Comment by yaitelmouden** [comment]
> From what I understand of the discussion above, since Noto Sans Tifinagh is a Neo-Tifinagh design, the solution here is to remove the special ligatures, so that's what I'll do.

@simoncozens 
If you mean the autogenerated ligatures (ⵏ+ⵏ=ⵏⵏ; ⵍ+ⵍ=ⵍⵍ), it's OK.
But the ligatures generated from the Tifinagh consonant joiner U2D7F (ⴼ⵿ⵜ; ⵙ⵿ⵜ; ⵎ⵿ⵜ; ⵏ⵿ⴾ; ...) can still without any problem.

**Comment by simoncozens** [comment]
Yes, just the yal/yan sloping ligatures.

**Comment by Yassine3649** [comment]
Guys its 2023 and the problem still exists. ⵏⵏ ⵏⵍ ⵍⵏ ⵍⵍ are uncorrect forms , yan should stay ⵏ and yal should stay ⵍ 
Please fix it

**Comment by simoncozens** [comment]
It's fixed in the font. People may need to install updates, but the font is fine.

**Comment by Yassine3649** [comment]
I am sorry i dont know a lot of stuff 
But how can i install the font on my phone ? Or is it only for pc ?

**Comment by simoncozens** [comment]
Recently the Android team gathered information for a Noto update, presumably to go in the 2023 release; it does happen periodically, and these days we have a good pipeline for delivering fonts to them. This time, unfortunately, it was before the new version of Tifinagh was released, so the next Android release will get the old one. The Android release *after that* should have the fixed Tifinagh.
