### ISSUE TITLE
Missing diaeresis in Tifinagh

### ISSUE THREAD

**Issue by dscorbett** [notofonts/tifinagh#3]
### Font
NotoSansTifinagh-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansTifinagh-unhinted.zip
Date: 2017-11-28

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
[One Tifinagh orthography uses U+0308 COMBINING DIAERESIS](http://hapax.qc.ca/polices/inventaire-des-oeils.pdf#page=21), but Noto Sans Tifinagh does not support it.

### Character data
ⵝ̈ⵉ̈
U+2D5D TIFINAGH LETTER YATH
U+0308 COMBINING DIAERESIS
U+2D49 TIFINAGH LETTER YI
U+0308 COMBINING DIAERESIS

**Comment by simoncozens** [comment]
Now that we have full builds with Noto Sans Latin core subsets, this glyph will be added.
