### ISSUE TITLE
Bad combination of dot and macron in Tifinagh

### ISSUE THREAD

**Issue by dscorbett** [notofonts/tifinagh#4]
### Font
NotoSansTifinagh-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansTifinagh-unhinted.zip
Date: 2017-11-28

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
The combination of a dot and a macron [should be centered above the base](http://hapax.qc.ca/pour-aix/R%C3%A9pertoires.jpg) instead of favoring the right side. The dot and the macron should have the same vertical position, but the macron is currently lower than the dot.

### Character data
ⵉ̇̄ⴵ̇̄
U+2D49 TIFINAGH LETTER YI
U+0307 COMBINING DOT ABOVE
U+0304 COMBINING MACRON
U+2D35 TIFINAGH LETTER BERBER ACADEMY YAJ
U+0307 COMBINING DOT ABOVE
U+0304 COMBINING MACRON

### Screenshot
![ⵉ̇̄ⴵ̇̄](https://user-images.githubusercontent.com/1124347/39778617-cf5b3700-52d4-11e8-912a-9aa8af4ef836.png)

**Comment by simoncozens** [comment]
Things appear to have got impressively worse:
![shape](https://user-images.githubusercontent.com/106728/189663670-7e989165-d558-4ad6-b184-ff85ff679652.png)

**Comment by dscorbett** [comment]
This is still broken in version 2.004.

**Comment by simoncozens** [comment]
Change `ccmp` to `rlig` fixes it again.

**Comment by moyogo** [comment]
> @moyogo broke it. ;-) But I am to blame for not adding tests to stop him breaking it.

How did adding languagesystem break it?

**Comment by simoncozens** [comment]
Probably because it’s now going through the USE and rules are being applied per cluster.
